@SubastaYa.API_HostAddress = http://localhost:5118

### Crear un usuario de prueba
POST https://localhost:7147/api/usuarios
Content-Type: application/json

{
  "nombreUsuario": "JuanPerez",
  "alias": "juanp",
  "email": "juan@example.com",
  "contrasenaHash": "hash12345"
}

### Obtener todos los usuarios
GET https://localhost:7147/api/usuarios
Accept: application/json
