// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubastaYa.API.Data;

#nullable disable

namespace SubastaYa.API.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260904004300_SemillasYTransaccionesIniciales")]
    partial class SemillasYTransaccionesIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.API.Models.Auditoria_Log", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle_Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsuarioFK")
                        .HasColumnType("integer");

                    b.HasKey("AuditoriaId");

                    b.HasIndex("UsuarioFK");

                    b.ToTable("Auditorias");

                    b.HasData(
                        new
                        {
                            AuditoriaId = 1,
                            Accion = "Creación de subasta",
                            Detalle_Json = "",
                            Entidad = "",
                            EntidadId = 1,
                            Fecha = new DateTime(2026, 9, 4, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(5969),
                            UsuarioFK = 1
                        },
                        new
                        {
                            AuditoriaId = 2,
                            Accion = "Creación de subasta",
                            Detalle_Json = "",
                            Entidad = "",
                            EntidadId = 2,
                            Fecha = new DateTime(2026, 9, 4, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(6307),
                            UsuarioFK = 1
                        },
                        new
                        {
                            AuditoriaId = 3,
                            Accion = "Creación de subasta",
                            Detalle_Json = "",
                            Entidad = "",
                            EntidadId = 3,
                            Fecha = new DateTime(2026, 9, 4, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(6309),
                            UsuarioFK = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Billetera", b =>
                {
                    b.Property<int>("BilleteraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BilleteraId"));

                    b.Property<decimal>("SaldoDisponible")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("\"SaldoTotal\" - \"SaldoRetenido\"", true);

                    b.Property<decimal>("SaldoRetenido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SaldoTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("UsuarioFK")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("BilleteraId");

                    b.HasIndex("UsuarioFK")
                        .IsUnique();

                    b.ToTable("Billeteras");

                    b.HasData(
                        new
                        {
                            BilleteraId = 1,
                            SaldoDisponible = 0m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 0m,
                            UsuarioFK = 1,
                            Version = 1
                        },
                        new
                        {
                            BilleteraId = 2,
                            SaldoDisponible = 0m,
                            SaldoRetenido = 45000m,
                            SaldoTotal = 150000m,
                            UsuarioFK = 2,
                            Version = 1
                        },
                        new
                        {
                            BilleteraId = 3,
                            SaldoDisponible = 0m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 200000m,
                            UsuarioFK = 3,
                            Version = 1
                        },
                        new
                        {
                            BilleteraId = 4,
                            SaldoDisponible = 0m,
                            SaldoRetenido = 0m,
                            SaldoTotal = 500m,
                            UsuarioFK = 4,
                            Version = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlIcono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Nombre = "Tecnologia",
                            UrlIcono = "bi-cpu"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Nombre = "Coleccionables",
                            UrlIcono = "bi-star"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Nombre = "Indumentaria",
                            UrlIcono = "bi-tshirt"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Nombre = "Vehiculos",
                            UrlIcono = "bi-car"
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Puja", b =>
                {
                    b.Property<int>("PujaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PujaId"));

                    b.Property<int>("CompradorFK")
                        .HasColumnType("integer");

                    b.Property<int?>("CompradorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoPuja")
                        .HasColumnType("numeric");

                    b.Property<int>("SubastaFK")
                        .HasColumnType("integer");

                    b.Property<int?>("SubastaId")
                        .HasColumnType("integer");

                    b.HasKey("PujaId");

                    b.HasIndex("CompradorFK");

                    b.HasIndex("SubastaFK");

                    b.ToTable("Pujas");

                    b.HasData(
                        new
                        {
                            PujaId = 1,
                            CompradorFK = 3,
                            FechaPuja = new DateTime(2026, 9, 4, 0, 33, 0, 276, DateTimeKind.Utc).AddTicks(8049),
                            MontoPuja = 30000m,
                            SubastaFK = 1
                        },
                        new
                        {
                            PujaId = 2,
                            CompradorFK = 2,
                            FechaPuja = new DateTime(2026, 9, 4, 0, 38, 0, 276, DateTimeKind.Utc).AddTicks(8709),
                            MontoPuja = 45000m,
                            SubastaFK = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Subasta", b =>
                {
                    b.Property<int>("SubastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubastaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioInicial")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoFK")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PujaMinima")
                        .HasColumnType("numeric");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VendedorFK")
                        .HasColumnType("integer");

                    b.Property<int?>("VendedorId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("SubastaId");

                    b.HasIndex("ProductoFK");

                    b.HasIndex("VendedorFK");

                    b.ToTable("Subastas");

                    b.HasData(
                        new
                        {
                            SubastaId = 1,
                            Descripcion = "Laptop de gama alta",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 4, 1, 13, 0, 276, DateTimeKind.Utc).AddTicks(2667),
                            FechaInicio = new DateTime(2026, 9, 4, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(2329),
                            PrecioInicial = 5000m,
                            ProductoFK = 1,
                            PujaMinima = 1000m,
                            Titulo = "Laptop",
                            UrlImagen = "https://picsum.photos/id/0/600/400",
                            VendedorFK = 1,
                            Version = 1
                        },
                        new
                        {
                            SubastaId = 2,
                            Descripcion = "Maquina de escribir vintage en buen estado",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 4, 0, 44, 18, 276, DateTimeKind.Utc).AddTicks(3115),
                            FechaInicio = new DateTime(2026, 9, 4, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(3114),
                            PrecioInicial = 50m,
                            ProductoFK = 2,
                            PujaMinima = 10m,
                            Titulo = "Maquina de escribir vintage",
                            UrlImagen = "https://picsum.photos/id/111/600/400",
                            VendedorFK = 1,
                            Version = 1
                        },
                        new
                        {
                            SubastaId = 3,
                            Descripcion = "Campera de invierno en buen estado",
                            Estado = "PROGRAMADA",
                            FechaFin = new DateTime(2026, 9, 7, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(3135),
                            FechaInicio = new DateTime(2026, 9, 5, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(3122),
                            PrecioInicial = 100m,
                            ProductoFK = 3,
                            PujaMinima = 300m,
                            Titulo = "Campera de invierno",
                            UrlImagen = "https://picsum.photos/id/338/600/400",
                            VendedorFK = 1,
                            Version = 1
                        },
                        new
                        {
                            SubastaId = 4,
                            Descripcion = "Autos antiguos en buen estado",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 1, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(3137),
                            FechaInicio = new DateTime(2026, 8, 30, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(3137),
                            PrecioInicial = 300m,
                            ProductoFK = 4,
                            PujaMinima = 1000m,
                            Titulo = "Autos antiguos",
                            UrlImagen = "https://picsum.photos/id/133/600/400",
                            VendedorFK = 1,
                            Version = 1
                        },
                        new
                        {
                            SubastaId = 5,
                            Descripcion = "Smartphone de última generación",
                            Estado = "ACTIVA",
                            FechaFin = new DateTime(2026, 9, 3, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(3140),
                            FechaInicio = new DateTime(2026, 9, 2, 0, 43, 0, 276, DateTimeKind.Utc).AddTicks(3139),
                            PrecioInicial = 800m,
                            ProductoFK = 1,
                            PujaMinima = 200m,
                            Titulo = "Smartphone",
                            UrlImagen = "https://picsum.photos/id/3/600/400",
                            VendedorFK = 1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.TransaccionLedger", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransaccionId"));

                    b.Property<int>("BilleteraFK")
                        .HasColumnType("integer");

                    b.Property<int?>("BilleteraFk")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<int?>("SubastaFK")
                        .HasColumnType("integer");

                    b.Property<int?>("SubastaFk")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransaccionId");

                    b.HasIndex("BilleteraFK");

                    b.HasIndex("SubastaFK");

                    b.ToTable("TransaccionesLedger");

                    b.HasData(
                        new
                        {
                            TransaccionId = 1,
                            BilleteraFK = 2,
                            Monto = 150000m,
                            TipoTransaccion = "DEPOSITO",
                            fecha = new DateTime(2026, 9, 3, 0, 43, 0, 277, DateTimeKind.Utc).AddTicks(1223)
                        },
                        new
                        {
                            TransaccionId = 2,
                            BilleteraFK = 3,
                            Monto = 200000m,
                            TipoTransaccion = "DEPOSITO",
                            fecha = new DateTime(2026, 9, 3, 0, 43, 0, 277, DateTimeKind.Utc).AddTicks(1558)
                        },
                        new
                        {
                            TransaccionId = 3,
                            BilleteraFK = 4,
                            Monto = 500m,
                            TipoTransaccion = "DEPOSITO",
                            fecha = new DateTime(2026, 9, 3, 0, 43, 0, 277, DateTimeKind.Utc).AddTicks(1567)
                        },
                        new
                        {
                            TransaccionId = 4,
                            BilleteraFK = 2,
                            Monto = -45000m,
                            SubastaFK = 1,
                            TipoTransaccion = "RETENCION",
                            fecha = new DateTime(2026, 9, 4, 0, 38, 0, 277, DateTimeKind.Utc).AddTicks(1569)
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Alias = "elque vende",
                            ContrasenaHash = "$2a$11$urzy5BQ.peX3CWqny04lauFiUj0fVTjFY.4FmR70caaI.zyw5/ap.",
                            Email = "vendedor@test.com",
                            FechaRegistro = new DateTime(2026, 9, 4, 0, 42, 59, 967, DateTimeKind.Utc).AddTicks(6824),
                            NombreUsuario = "Franco"
                        },
                        new
                        {
                            UsuarioId = 2,
                            Alias = "el que compra1",
                            ContrasenaHash = "$2a$11$tbCIZSbHxY.cs9RtvVZWZOYl/4V3WPsaX7zWt2EM..7esvrFZ7oNS",
                            Email = "comprador1@test.com",
                            FechaRegistro = new DateTime(2026, 9, 4, 0, 43, 0, 70, DateTimeKind.Utc).AddTicks(6812),
                            NombreUsuario = "Juan"
                        },
                        new
                        {
                            UsuarioId = 3,
                            Alias = "el que compra2",
                            ContrasenaHash = "$2a$11$Z/KGJtdWm.H9XLsCK3n7iuU3aO2fS98M50BN6tE2La8HtjKvvkcNW",
                            Email = "comprador2@test.com",
                            FechaRegistro = new DateTime(2026, 9, 4, 0, 43, 0, 172, DateTimeKind.Utc).AddTicks(6974),
                            NombreUsuario = "Pedro"
                        },
                        new
                        {
                            UsuarioId = 4,
                            Alias = "la que compra3",
                            ContrasenaHash = "$2a$11$J3L8oXjYSzLwhvHZircI3eoKINyoG2/BDo8uVrCJKjvAOqAieaXza",
                            Email = "sinfondos@test.com",
                            FechaRegistro = new DateTime(2026, 9, 4, 0, 43, 0, 275, DateTimeKind.Utc).AddTicks(4561),
                            NombreUsuario = "Maria"
                        });
                });

            modelBuilder.Entity("SubastaYa.API.Models.Auditoria_Log", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", null)
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioFK")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SubastaYa.API.Models.Billetera", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.API.Models.Billetera", "UsuarioFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Puja", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Subasta", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("ProductoFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("VendedorFK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.API.Models.TransaccionLedger", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Billetera", "Billetera")
                        .WithMany()
                        .HasForeignKey("BilleteraFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaFK")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Billetera");
                });
#pragma warning restore 612, 618
        }
    }
}
