// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SubastaYa.API.Data;

#nullable disable

namespace SubastaYa.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260903204957_MigracionEsquemaCompleto")]
    partial class MigracionEsquemaCompleto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SubastaYa.API.Models.Auditoria_Log", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalle_Json")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntidadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsuarioFK")
                        .HasColumnType("integer");

                    b.HasKey("AuditoriaId");

                    b.HasIndex("UsuarioFK");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Billetera", b =>
                {
                    b.Property<int>("BilleteraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BilleteraId"));

                    b.Property<decimal>("SaldoDisponible")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric")
                        .HasComputedColumnSql("\"SaldoTotal\" - \"SaldoRetenido\"", true);

                    b.Property<decimal>("SaldoRetenido")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SaldoTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("BilleteraId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Billeteras");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlIcono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Puja", b =>
                {
                    b.Property<int>("PujaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PujaId"));

                    b.Property<int>("CompradorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaPuja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MontoPuja")
                        .HasColumnType("numeric");

                    b.Property<int>("SubastaId")
                        .HasColumnType("integer");

                    b.HasKey("PujaId");

                    b.HasIndex("CompradorId");

                    b.HasIndex("SubastaId");

                    b.ToTable("Pujas");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Subasta", b =>
                {
                    b.Property<int>("SubastaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubastaId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PrecioInicial")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PujaMinima")
                        .HasColumnType("numeric");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VendedorId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("SubastaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VendedorId");

                    b.ToTable("Subastas");
                });

            modelBuilder.Entity("SubastaYa.API.Models.TransaccionLedger", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransaccionId"));

                    b.Property<int>("BilleteraFk")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("numeric");

                    b.Property<int?>("SubastaFk")
                        .HasColumnType("integer");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransaccionId");

                    b.HasIndex("BilleteraFk");

                    b.HasIndex("SubastaFk");

                    b.ToTable("TransaccionesLedger");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Auditoria_Log", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", null)
                        .WithMany("Auditorias")
                        .HasForeignKey("UsuarioFK")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("SubastaYa.API.Models.Billetera", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", "Usuario")
                        .WithOne("Billetera")
                        .HasForeignKey("SubastaYa.API.Models.Billetera", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Puja", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Usuario", "Comprador")
                        .WithMany()
                        .HasForeignKey("CompradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comprador");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Subasta", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("VendedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SubastaYa.API.Models.TransaccionLedger", b =>
                {
                    b.HasOne("SubastaYa.API.Models.Billetera", "Billetera")
                        .WithMany()
                        .HasForeignKey("BilleteraFk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SubastaYa.API.Models.Subasta", "Subasta")
                        .WithMany()
                        .HasForeignKey("SubastaFk")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Billetera");

                    b.Navigation("Subasta");
                });

            modelBuilder.Entity("SubastaYa.API.Models.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Billetera");
                });
#pragma warning restore 612, 618
        }
    }
}
